export enum MESSAGES {
  INIT_AUTOFILL_ALL = 'INIT_AUTOFILL_ALL',
  INIT_AUTOFILL_SINGLE = 'INIT_AUTOFILL_SINGLE',
  AUTOFILL_RUNNING = 'AUTOFILL_RUNNING',
  AUTOFILL_COMPLETE = 'AUTOFILL_COMPLETE',
  AUTOFILL_ERROR = 'AUTOFILL_ERROR',
}

export const DEFAULT_CONFIG = {
  enableTypeEffect: true,
  typeEffectSpeed: 50,
  forceAutofill: false,
}
