export enum MESSAGES {
  POPUP_OPENED = 'POPUP_OPENED',
  SCROLL_FORM_INTO_VIEW = 'SCROLL_FORM_INTO_VIEW',
  INIT_AUTOFILL_ALL = 'INIT_AUTOFILL_ALL',
  INIT_AUTOFILL_SINGLE = 'INIT_AUTOFILL_SINGLE',
  AUTOFILL_RUNNING = 'AUTOFILL_RUNNING',
  AUTOFILL_COMPLETE = 'AUTOFILL_COMPLETE',
  AUTOFILL_ERROR = 'AUTOFILL_ERROR',
}

export const DEFAULT_CONFIG = {
  enableTypeEffect: true,
  typeEffectSpeed: 200,
  forceAutofill: false,
}

export const EXTENSION_ID = chrome.i18n.getMessage('@@extension_id')
