import { SupportedInputsType } from '@/types'
import { useContentScriptStore as contentScriptStore } from '@/store/content-script'
import { invalidateMatchCache, log } from '@/utils'
import { isFeatureEnabled } from '@/utils/featureFlags'

import { gatherContenteditableHosts, gatherVisibleInputsInOrder, gatherWidgetElements, fillElement, waitForSettle } from '.'
import { resetRecipeRun, runRecipesPass } from './recipes'

interface IinitiateAutofill {
  rootElement: Element | null
}

export const initiateAutofill = async ({ rootElement }: IinitiateAutofill) => {
  // Reset per-run shared values so a fresh fill doesn't reuse the name/password
  // generated by a previous run. These are only meant to stay consistent across
  // fields *within* a single autofill pass (e.g. email matches name, confirm
  // password matches password).
  contentScriptStore.setState({ firstName: undefined, lastName: undefined, lastGeneratedPassword: '' })

  // Drop cached per-element match text so this run re-reads labels/attributes
  // (the page may have changed since the last fill).
  invalidateMatchCache()

  /* Inputs */
  const inputs = gatherVisibleInputsInOrder(rootElement)

  log(`Initially found ${inputs.length} visible input elements`)

  await autoFillInputsSequentially({ inputs })

  // Check for any inputs that have mounted after focus (for eg: Stripe checkout form) —
  // give late renders a moment to settle before re-gathering.
  await waitForSettle(rootElement ?? document.body, { timeoutMs: 800 })
  const finalInputs = gatherVisibleInputsInOrder(rootElement)
  const newInputs = finalInputs.filter((input) => !inputs.includes(input))

  if (newInputs.length > 0) await autoFillInputsSequentially({ inputs: newInputs })

  /* User-defined recipes — taught interactions outrank built-in widget adapters
     and can drive fully custom elements no adapter recognizes. */
  resetRecipeRun()
  if (isFeatureEnabled('recipes')) await runRecipesPass(rootElement)

  /* Custom widgets (ARIA comboboxes, date pickers, switches…) */
  const widgets = gatherWidgetElements(rootElement)

  log(`Found ${widgets.length} widget elements`)

  for (const elem of widgets) {
    await fillElement({ elem })
  }

  /* Contenteditable hosts (rich-text editors, editable divs) — scoped and visibility-filtered */
  const contenteditableHosts = gatherContenteditableHosts(rootElement)

  log(`Found ${contenteditableHosts.length} contenteditable hosts`)

  for (const elem of contenteditableHosts) {
    await fillElement({ elem })
  }

  /* iframe */
  // const iframes = document.querySelectorAll('iframe')
  // const iframesWithForms = Array.from(iframes).filter((iframe) => {
  //   try {
  //     const iframeDoc = iframe.contentDocument || iframe.contentWindow?.document
  //     return iframeDoc && (iframeDoc.querySelector('input') !== null || iframeDoc.querySelector('form') !== null)
  //   } catch (e) {
  //     // If we can't access the iframe's content due to same-origin policy, ignore it
  //     return false
  //   }
  // })

  // console.log(iframesWithForms)

  // log(`Found ${iframesWithForms.length} iframes with input or form elements`)
}

interface IautoFillInputsSequentially {
  inputs: SupportedInputsType[]
}

const autoFillInputsSequentially = async ({ inputs }: IautoFillInputsSequentially) => {
  for (const input of inputs) {
    await fillElement({ elem: input })
  }
}
