name: Extension Continuos Integration

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Set Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Build and zip the build (dist) folder
        run: pnpm run build:extension && pnpm run postbuild

      - name: Get package.json data
        uses: codex-team/action-nodejs-package-info@v1.1
        id: package

      - name: Upload extension to Chrome Web Store
        uses: mobilefirstllc/cws-publish@latest
        with:
          action: "upload"
          client_id: ${{ secrets.CHROME_WEB_STORE_CLIENT_ID }}
          client_secret: ${{ secrets.CHROME_WEB_STORE_CLIENT_SECRET }}
          refresh_token: ${{ secrets.CHROME_WEB_STORE_REFRESH_TOKEN }}
          extension_id: ${{ secrets.CHROME_WEB_STORE_EXTENSION_ID }}
          zip_file: ./deploy/${{ steps.package.outputs.name }}-v${{ steps.package.outputs.version }}.zip

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.package.outputs.name }}-v${{ steps.package.outputs.version }}
          path: ./deploy/*.zip
          retention-days: 7
